### PR TITLE
Migrate to ArrayInterface v7, move Julia minimum version to 1.6

### PR DESCRIPTION
**Pull request by BioTurboNick**

### CODE REVIEW

**Comment by BioTurboNick** [comment]
Seems it may also need to add https://github.com/JuliaArrays/StaticArrayInterface.jl as a dependency?

**Comment by timholy** [comment]
If so, I'm fine with that.

**Comment by BioTurboNick** [comment]
Apparently everything directly needed from ArrayInterface moved to StaticArrayInterface, and ArrayInterface 7 is a dependency of StaticArrayInterface.

But StaticArrayInterface is not compatible with Julia 1.2. Can support for 1.2 be dropped?

**Comment by timholy** [comment]
Yes. Obviously we need to bump to 0.5. Should we just go straight to 1.0? I am not seeing the reasons to keep have 0.x releases for a package which is changing only slowly.

**Comment by BioTurboNick** [comment]
Good question - there is the one PR that, while old, seems to indicate a need for a better API? Maybe I can take a look at it.

**Comment by timholy** [comment]
Thanks! I don't mean this package won't change in the future: there's a chance I'll have an extended period where I'll rework a lot of JuliaImages (ideally as grant-funded work). So if you'd rather hold off on 1.0 because you think there are some major changes needed, that's perfectly fine.

**Comment by laborg** [comment]
Could you please merge this PR and release a new version? I got some precompliation warnings because the compat bound trickeled down to me through ImageFiltering.jl

**Comment by BioTurboNick** [comment]
@timholy - sorry to bug you, could you please merge and register this quick?

**Comment by BioTurboNick** [comment]
Oh I guess StaticArrayInterface needs a simple compat entry for the registration to go through, right?

**Pull request merged**
